PREFIX          = ../..
COLLFILES       = collection.omdoc
BUTFILES 	= catalogue.omdoc pvs.omdoc# collection.omdoc
include $(PREFIX)/lib/Makefile.vars

all:		html ps mml 
collection:	collection.html collection.xml collection.ps
include $(PREFIX)/lib/Makefile.in
