PREFIX          = ../../..
include $(PREFIX)/lib/Makefile.vars
BUTFILES	= prefixed.omdoc
NEEDSFROMDIRS	= ../../../examples/logics ../../../examples/omstd

all:		html mml #recurse #ps
include $(PREFIX)/lib/Makefile.in

recurse:	
#		if(cd lecture4 && $(MAKE) -$(MAKEFLAGS)); then true; else exit 1; fi
